services:
  magicvilla_villaapi:
    container_name: magicvilla_villaapi
    image: ${DOCKER_REGISTRY-}magicvillavillaapi
    build:
      context: .
      dockerfile: MagicVilla_VillaAPI/Dockerfile
    ports:
        - "5000:80"

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
volumes:
    sql_data:
        